MVC_workshop/Models/Enrollment.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_workshop.Models
{
    public class Enrollment
    {
        public int Id { get; set; }

        [Display(Name = "Semester")]
        [StringLength(10)]
        public string? Semester { get; set; }

        [Display(Name = "Year")]
        public int? Year { get; set; }

        [Display(Name = "Grade")]
        public int? Grade { get; set; }

        [Display(Name = "Seminal Url")]
        [StringLength(255)]
        public string? SeminalUrl { get; set; }

        [Display(Name = "Project Url")]
        [StringLength(255)]
        public string? ProjectUrl { get; set; }

        [Display(Name = "Exam Points")]
        public int? ExamPoints { get; set; }

        [Display(Name = "Seminal Points")]
        public int? SeminalPoints { get; set; }

        [Display(Name = "Project Points")]
        public int? ProjectPoints { get; set; }

        [Display(Name = "Additional Points")]
        public int? AdditionalPoints { get; set; }

        [Display(Name = "Finish Date")]
        [DataType(DataType.Date)]
        public DateTime? FinishDate { get; set; }

        [Required]
        public int CourseId { get; set; }

        public Course? Course { get; set; }

        [Required]
        public int StudentId { get; set; }
        public Student? Student { get; set; }
    }
}

MVC_workshop/Controllers/EnrollmentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_workshop.Data;
using MVC_workshop.Models;
using MVC_workshop.ViewModels;

namespace MVC_workshop.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly MVC_workshopContext _context;

        public EnrollmentsController(MVC_workshopContext context)
        {
            _context = context;
        }

        // GET: Enrollments
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var mVC_workshopContext = _context.Enrollments.Include(e => e.Course).Include(e => e.Student);
            return View(await mVC_workshopContext.ToListAsync());
        }

        // GET: Enrollments/Details/5
        [Authorize(Roles = "Admin,Student,Teacher")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // GET: Enrollments/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Title");
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "FirstName");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate,CourseId,StudentId")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "FirstName", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "FirstName", enrollment.StudentId);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate,CourseId,StudentId")] Enrollment enrollment)
        {
            if (id != enrollment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "FirstName", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enrollment = await _context.Enrollments.FindAsync(id);
            _context.Enrollments.Remove(enrollment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnrollmentExists(int id)
        {
            return _context.Enrollments.Any(e => e.Id == id);
        }
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> StudentsEnCourse(int? id,  string? tname, int year)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = await _context.Courses
                .FindAsync(id);
            string[] tnames = tname.Split(" ");
            var teacher = _context.Teachers.Where(x => x.FirstName==tnames[0] && x.LastName==tnames[1]).First();
            ViewBag.teacher = teacher.FullName;
            ViewBag.course = course.Title;
            var enrollment = _context.Enrollments.Where(x => x.CourseId==id )
                .Include(e => e.Course)
            .Include(e => e.Student);
            await _context.SaveChangesAsync();
            IQueryable<int?> yearsq = _context.Enrollments.OrderBy(m => m.Year).Select(m => m.Year).Distinct();
            IQueryable<Enrollment> enrollmentq = enrollment.AsQueryable();
            if (year != null && year != 0)
            {
                enrollmentq = enrollmentq.Where(x => x.Year == year);
            }
            else
            {
                enrollmentq = enrollmentq.Where(x => x.Year == yearsq.Max());
            }

            if (enrollment == null)
            {
                return NotFound();
            }
            EnrollmentVM vm = new EnrollmentVM
            {
                Enrollments = await enrollmentq.ToListAsync(),
                Years = new SelectList(await yearsq.ToListAsync())
            };

            return View(vm);
        }
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> CoursesStudent(int? id, string? userID)
        {
            if (userID != null)
            {
                var st = await _context.Students.FirstOrDefaultAsync(x => x.userId == userID);
                id = st.Id;
            }
            if (id == null)
            {
                return NotFound();
            }
            var student = await _context.Students.FirstOrDefaultAsync(m => m.Id == id);
            IQueryable<Enrollment> enrollments = _context.Enrollments.Where(x => x.StudentId == student.Id)
                .Include(e => e.Course)
                .Include(e => e.Student);
            var studentID = await _context.Students.FindAsync(id);
            ViewBag.Student = student.FullName;
            await _context.SaveChangesAsync();
            return View(await enrollments.ToListAsync());
        }
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> StudentEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var enrollment = _context.Enrollments.Where(x => x.Id == id).Include(x => x.Student).Include(x => x.Course).First();
            IQueryable<Enrollment> enrollmentq = _context.Enrollments.AsQueryable();
            enrollmentq = enrollmentq.Where(x => x.Id == id);
            if (enrollment == null)
            {
                return NotFound();
            }
            StudentEditVM vm = new StudentEditVM
            {
                enrollment = await enrollmentq.Include(x => x.Student).Include(x => x.Course).FirstAsync(),
                seminalUrl = enrollment.SeminalUrl

            };
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Title", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Students, "Id", "FirstName", enrollment.StudentId);
            return View(vm);
        }
        [Authorize(Roles = "Student")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> StudentEdit(int id, StudentEditVM vm)
        {
            if (id != vm.enrollment.Id)
            {

MVC_workshop/Views/Enrollments/CoursesStudent.cshtml
@model IEnumerable<MVC_workshop.Models.Enrollment>

@{
    ViewData["Title"] = "CoursesStudent";
}

<h1 align="center">@ViewBag.Student - courses</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SeminalUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExamPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SeminalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdditionalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FinishDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
             <td>
                @Html.DisplayFor(modelItem => item.Course.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @if(@item.SeminalUrl==null){
                    <p>No file uploaded</p>
                }
                else{
                    <a href="~/seminals/@item.SeminalUrl">Open file</a>
                }
            </td>
            <td>
                @if(@item.ProjectUrl==null){
                    <p>No link uploaded</p>
                }
                else{
                    <a href="@item.ProjectUrl">Open link</a>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExamPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeminalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdditionalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishDate)
            </td>
            <td>
                <a asp-action="StudentEdit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

MVC_workshop/Views/Enrollments/Create.cshtml
@model MVC_workshop.Models.Enrollment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Enrollment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalUrl" class="control-label"></label>
                <input asp-for="SeminalUrl" class="form-control" />
                <span asp-validation-for="SeminalUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectUrl" class="control-label"></label>
                <input asp-for="ProjectUrl" class="form-control" />
                <span asp-validation-for="ProjectUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamPoints" class="control-label"></label>
                <input asp-for="ExamPoints" class="form-control" />
                <span asp-validation-for="ExamPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalPoints" class="control-label"></label>
                <input asp-for="SeminalPoints" class="form-control" />
                <span asp-validation-for="SeminalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPoints" class="control-label"></label>
                <input asp-for="ProjectPoints" class="form-control" />
                <span asp-validation-for="ProjectPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalPoints" class="control-label"></label>
                <input asp-for="AdditionalPoints" class="form-control" />
                <span asp-validation-for="AdditionalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input asp-for="FinishDate" class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class ="form-control" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class ="form-control" asp-items="ViewBag.StudentId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_workshop/Views/Enrollments/Delete.cshtml
@model MVC_workshop.Models.Enrollment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdditionalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC_workshop/Views/Enrollments/Details.cshtml
@model MVC_workshop.Models.Enrollment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdditionalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.FirstName)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
        <span>|</span><a asp-action="Index">Back to List</a>
    }
    @if (User.Identity.IsAuthenticated && User.IsInRole("Student"))
    {
        <a asp-action="StudentEdit" asp-route-id="@Model?.Id">Edit</a>
    }
    @if (User.Identity.IsAuthenticated && User.IsInRole("Teacher")){
                    
    <a asp-controller="Courses" asp-action="CoursesTeacher" asp-route-id="@Model?.CourseId">Back to Courses</a>
    }

</div>

MVC_workshop/Views/Enrollments/StudentsEnCourse.cshtml
@model MVC_workshop.ViewModels.EnrollmentVM
@{
    ViewData["Title"] = "Index";
}

<h1 align="center">@ViewBag.course students, teacher - @ViewBag.teacher</h1>
<br/>
<form asp-controller="Enrollments" asp-action="StudentsEnCourse" asp-route-tname="@ViewBag.teacher">
    <p>
        <select asp-for="Year" asp-items="Model.Years">
            <option>Select year</option>
        </select>
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Student)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].SeminalUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].ProjectUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].ExamPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].SeminalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].ProjectPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].AdditionalPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].FinishDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Enrollments) {
        <tr>
             
            <td>
                @Html.DisplayFor(modelItem => item.Student.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @if(@item.SeminalUrl==null){
                    <p>No file uploaded</p>
                }
                else{
                    <a href="~/seminals/@item.SeminalUrl">Open file</a>
                }
            </td>
            <td>
                @if(@item.ProjectUrl==null){
                    <p>No link uploaded</p>
                }
                else{
                    <a href="@item.ProjectUrl">Open link</a>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExamPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeminalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdditionalPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishDate)
            </td>
            <td>
                    @if (@item.FinishDate == null)
                    {
                        <a asp-action="TeacherEdit" asp-route-id="@item.Id" asp-route-tname="@ViewBag.teacher">Edit</a> 
                    }
                | <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>