MVC_workshop/Models/Teacher.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_workshop.Models
{
    public class Teacher
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [StringLength(50)]
        [Display(Name = "Degree")]
        public string? Degree { get; set; }

        [StringLength(25)]
        [Display(Name = "Academic Rank")]
        public string? AcademicRank { get; set; }

        [StringLength(10)]
        [Display(Name = "Office Number")]
        public string? OfficeNumber { get; set; }

        public string? Picture { get; set; }
        public string? userId { get; set; }


        public string FullName
        {
            get { return FirstName + " " + LastName; }
        }
        [Display(Name = "Hire Date")]
        [DataType(DataType.Date)]
        public DateTime? HireDate { get; set; }
        public ICollection<Course>? CoursesF { get; set; }
        public ICollection<Course>? CoursesS { get; set; }
    }
}

MVC_workshop/Controllers/TeachersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_workshop.Data;
using MVC_workshop.Models;
using MVC_workshop.ViewModels;

namespace MVC_workshop.Controllers
{
    public class TeachersController : Controller
    {
        private readonly MVC_workshopContext _context;

        public TeachersController(MVC_workshopContext context)
        {
            _context = context;
        }

        // GET: Teachers
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string searchString)
        {
                var teachers = from t in _context.Teachers.Include(m => m.CoursesF)
                    .Include(m => m.CoursesS)
                               select t;
                if (!String.IsNullOrEmpty(searchString))
                {
                    teachers = teachers.Where(s => s.FirstName!.Contains(searchString) || s.LastName!.Contains(searchString) || s.Degree!.Contains(searchString) || s.AcademicRank!.Contains(searchString));
                }
                return View(await teachers.ToListAsync());
            
        }

        // GET: Teachers/Details/5
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Details(int? id,string? userID)
        {
            if (userID != null)
            {
                var tc = await _context.Teachers.FirstOrDefaultAsync(x => x.userId == userID);
                id = tc.Id;
            }
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            Teacher_EditPicture vm = new Teacher_EditPicture
            {
                teacher = teacher,
                pictureName = teacher.Picture
            };
            return View(vm);
        }
        [Authorize(Roles = "Admin")]
        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate,Picture")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            Teacher_EditPicture vm = new Teacher_EditPicture
            {
                teacher = teacher,
                pictureName = teacher.Picture
            };
            return View(vm);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Teacher_EditPicture vm)
        {
            if (id != vm.teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (vm.pictureFile != null)
                    {
                        string uniqueFileName = UploadedFile(vm);
                        vm.teacher.Picture = uniqueFileName;
                    }
                    else
                    {
                        vm.teacher.Picture = vm.pictureName;
                    }

                    _context.Update(vm.teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(vm.teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = vm.teacher.Id });
            }
            return View(vm);
        }

        // GET: Teachers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teachers.FindAsync(id);
            IQueryable<Course> courses = _context.Courses.AsQueryable();
            IQueryable<Course> courses1=courses.Where(s=>s.FirstTeacherId == id);
            IQueryable<Course> courses2 = courses.Where(s => s.SecondTeacherId == id);
            foreach(var course in courses1)
            {
                course.FirstTeacherId = null;
            }
            foreach(var course in courses2)
            {
                course.SecondTeacherId = null;
            }
            _context.Teachers.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teachers.Any(e => e.Id == id);
        }
        private string UploadedFile(Teacher_EditPicture vm)
        {
            string uniqueFileName = null;

            if (vm.pictureFile != null)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/pictures");
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(vm.pictureFile.FileName);
                string fileNameWithPath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    vm.pictureFile.CopyTo(stream);
                }
            }
            return uniqueFileName;
        }

    }
}

MVC_workshop/Views/Teachers/Create.cshtml
@model MVC_workshop.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcademicRank" class="control-label"></label>
                <input asp-for="AcademicRank" class="form-control" />
                <span asp-validation-for="AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNumber" class="control-label"></label>
                <input asp-for="OfficeNumber" class="form-control" />
                <span asp-validation-for="OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_workshop/Views/Teachers/Delete.cshtml
@model MVC_workshop.Models.Teacher

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AcademicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC_workshop/Views/Teachers/Details.cshtml
@model MVC_workshop.ViewModels.Teacher_EditPicture

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
           Profile picture:
        </dt>
        <dd class = "col-sm-10">
            <img src="~/pictures/@Model.teacher.Picture"
                class="rounded-circle"
                height="40" width="40"
                asp-append-version="true" />
        </dd> 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.Degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.AcademicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.AcademicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.OfficeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.OfficeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.teacher.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.teacher.HireDate)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.teacher.Id">Edit</a>
        <span>|</span><a asp-action="Index">Back to List</a>
    }
    @if (User.Identity.IsAuthenticated && User.IsInRole("Teacher"))
    {
        <a asp-controller="Home" asp-action="Index">Back</a>
    }
</div>

MVC_workshop/Views/Teachers/Edit.cshtml
@model MVC_workshop.ViewModels.Teacher_EditPicture

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="teacher.Id" />
            <div class="form-group">
                <label asp-for="pictureFile" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="pictureFile" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile"></label>
                </div>
                <span asp-validation-for="pictureFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="teacher.FirstName" class="control-label"></label>
                <input asp-for="teacher.FirstName" class="form-control" />
                <span asp-validation-for="teacher.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="teacher.LastName" class="control-label"></label>
                <input asp-for="teacher.LastName" class="form-control" />
                <span asp-validation-for="teacher.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="teacher.Degree" class="control-label"></label>
                <input asp-for="teacher.Degree" class="form-control" />
                <span asp-validation-for="teacher.Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="teacher.AcademicRank" class="control-label"></label>
                <input asp-for="teacher.AcademicRank" class="form-control" />
                <span asp-validation-for="teacher.AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="teacher.OfficeNumber" class="control-label"></label>
                <input asp-for="teacher.OfficeNumber" class="form-control" />
                <span asp-validation-for="teacher.OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="teacher.HireDate" class="control-label"></label>
                <input asp-for="teacher.HireDate" class="form-control" />
                <span asp-validation-for="teacher.HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="teacher.userId" class="control-label"></label>
                <input asp-for="teacher.userId" class="form-control" />
                <span asp-validation-for="teacher.userId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_workshop/Views/Teachers/Index.cshtml
@model IEnumerable<MVC_workshop.Models.Teacher>

@{
    ViewData["Title"] = "Index";
}

<h1 align="center">Teachers</h1>

<p>
    <a asp-action="Create" class="btn btn-secondary mb-3">New Teacher</a>
</p>
<form asp-controller="Teachers" asp-action="Index" method="get">
    <p>
        Search: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AcademicRank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfficeNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HireDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Degree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AcademicRank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficeNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HireDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>