MVC_workshop/Controllers/CoursesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_workshop.Data;
using MVC_workshop.Models;
using MVC_workshop.ViewModels;
using Microsoft.AspNetCore.Identity;
using MVC_workshop.Areas.Identity.Data;


namespace MVC_workshop.Controllers
{
    public class CoursesController : Controller
    {
        private readonly MVC_workshopContext _context;

        public CoursesController(MVC_workshopContext context)
        {
            _context = context;
        }

        // GET: Courses
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string searchString)
        {
            var courses = from c in _context.Courses.Include(m => m.Enrollments)
                                               .ThenInclude(m => m.Student)
                          select c;
            if (!String.IsNullOrEmpty(searchString))
            {
                int br;
                bool isNumber = int.TryParse(searchString, out br);
                if (isNumber)
                {
                    courses = courses.Where(s => s.Semester == br);
                }
                else
                {
                    courses = courses.Where(s => s.Title!.Contains(searchString) || s.Programme!.Contains(searchString));
                }
            }
            return View(await courses.ToListAsync());
        }
        /*public async Task<IActionResult> Index(int Id)
        {
            var courses = from c in _context.Courses
                          select c;
            courses = courses.Where(s => s.FirstTeacherId == Id || s.SecondTeacherId==Id);
            return View(await courses.ToListAsync());
        }*/
        // GET: Courses/Details/5
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["FirstTeacherId"] = new SelectList(_context.Teachers, "Id", "FirstName");
            ViewData["SecondTeacherId"] = new SelectList(_context.Teachers, "Id", "FirstName");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FirstTeacherId"] = new SelectList(_context.Teachers, "Id", "FirstName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teachers, "Id", "FirstName", course.SecondTeacherId);
            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = _context.Courses.Where(x => x.Id == id).Include(x => x.Enrollments).First();
            IQueryable<Course> coursesq = _context.Courses.AsQueryable();
            coursesq = coursesq.Where(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }
            var students = _context.Students.AsEnumerable();
            students = students.OrderBy(s => s.FullName);
            EnrollMoreStudents vm = new EnrollMoreStudents
            {
                // course = course,
                course = await coursesq.Include(x => x.FirstTeacher).Include(x => x.SecondTeacher).FirstAsync(),
                studentsList = new MultiSelectList(students, "Id", "FullName"),
                selectedStudents = course.Enrollments.Select(x => x.StudentId)
            };
            ViewData["FirstTeacherId"] = new SelectList(_context.Teachers, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teachers, "Id", "FullName", course.SecondTeacherId);
            ViewBag.Message = vm.course.Title;
            return View(vm);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EnrollMoreStudents vm)
        {
            if (id != vm.course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vm.course);
                    await _context.SaveChangesAsync();
                    var course = await _context.Courses.FindAsync(id);
                    string sem;
                    if (course.Semester % 2 == 0)
                    {
                        sem = "leten";
                    }
                    else
                    {
                        sem = "zimski";
                    }
                    IEnumerable<int> listStudents = vm.selectedStudents;
                    if (listStudents != null)
                    {
                        IQueryable<Enrollment> toBeRemoved = _context.Enrollments.Where(s => !listStudents.Contains(s.Student.Id) && s.CourseId == id);
                        _context.Enrollments.RemoveRange(toBeRemoved);
                        IEnumerable<int> exist = _context.Enrollments.Where(x => listStudents.Contains(x.Student.Id) && x.CourseId == id).Select(x => x.Student.Id);
                        IEnumerable<int> newEn = listStudents.Where(x => !exist.Contains(x));

                        foreach (int student in newEn)
                            _context.Add(new Enrollment { Semester = sem, Year = (int)vm.Year, StudentId = student, CourseId = id });

                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        IQueryable<Enrollment> toBeRemoved = _context.Enrollments.Where(s => s.CourseId == id);
                        _context.Enrollments.RemoveRange(toBeRemoved);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(vm.course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(vm);
        }
        [Authorize(Roles = "Admin")]
        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> CoursesTeacher(int? id,string? userID, string searchString)
        {
            if (userID != null)
            {
                var tc = await _context.Teachers.FirstOrDefaultAsync(x => x.userId == userID);
                id = tc.Id;
            }
            if (id == null)
            {
                return NotFound();
            }
            var teacher = await _context.Teachers.FirstOrDefaultAsync(x => x.Id == id);
            ViewBag.Teacher = teacher.FullName;
            IQueryable<Course> coursesq = _context.Courses.Where(x => x.FirstTeacherId == id || x.SecondTeacherId==id);
            if (!String.IsNullOrEmpty(searchString))
            {
                int br;
                bool isNumber = int.TryParse(searchString, out br);
                if (isNumber)
                {
                    coursesq = coursesq.Where(s => s.Semester == br);
                }
                else
                {
                    coursesq = coursesq.Where(s => s.Title!.Contains(searchString) || s.Programme!.Contains(searchString));
                }
            }
            await _context.SaveChangesAsync();

MVC_workshop/Controllers/StudentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_workshop.Data;
using MVC_workshop.Models;
using MVC_workshop.ViewModels;

namespace MVC_workshop.Controllers
{
    public class StudentsController : Controller
    {
        private readonly MVC_workshopContext _context;

        public StudentsController(MVC_workshopContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Admin")]
        // GET: Students
        public async Task<IActionResult> Index(string searchString)
        {
            var students = from s in _context.Students
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.FirstName!.Contains(searchString) || s.LastName!.Contains(searchString) || s.StudentId!.Contains(searchString));
            }
            return View(await students.ToListAsync());
        }

        // GET: Students/Details/5
        [Authorize(Roles = "Admin,Student")]
        public async Task<IActionResult> Details(int? id, string? userID)
        {
            if (userID != null)
            {
                var st = await _context.Students.FirstOrDefaultAsync(x => x.userId == userID);
                id = st.Id;
            }
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            Student_EditPicture vm = new Student_EditPicture
            {
                student = student,
                pictureName = student.Picture
            };
            return View(vm);
        }

        // GET: Students/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentId,FirstName,LastName,EnrollmentDate,AcquiredCredits,CurrentSemestar,EducationLevel,Picture")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            Student_EditPicture vm = new Student_EditPicture
            {
                student = student,
                pictureName = student.Picture
            };
            return View(vm);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Student_EditPicture vm)
        {
            if (id != vm.student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (vm.pictureFile != null)
                    {
                        string uniqueFileName = UploadedFile(vm);
                        vm.student.Picture = uniqueFileName;
                    }
                    else
                    {
                        vm.student.Picture = vm.pictureName;
                    }
                    _context.Update(vm.student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(vm.student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = vm.student.Id });
            }
            return View(vm);
        }

        // GET: Students/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Students.Any(e => e.Id == id);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> StudentsCourse(int? id, string searchString)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course= await _context.Courses.FindAsync(id);
            ViewBag.Message = course.Title;
            IQueryable<Student> studentsq = _context.Enrollments.Where(x => x.CourseId == id).Select(x => x.Student);
            if (!String.IsNullOrEmpty(searchString))
            {
                studentsq = studentsq.Where(s => s.FirstName!.Contains(searchString) || s.LastName!.Contains(searchString) || s.StudentId!.Contains(searchString));
            }
            return View(await studentsq.ToListAsync());
            await _context.SaveChangesAsync();
            return View(await studentsq.ToListAsync());

        }
       
        private string UploadedFile(Student_EditPicture vm)
        {
            string uniqueFileName = null;

            if (vm.pictureFile != null)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/pictures");
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(vm.pictureFile.FileName);
                string fileNameWithPath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    vm.pictureFile.CopyTo(stream);
                }
            }
            return uniqueFileName;
        }
    }
}

MVC_workshop/Views/Courses/CoursesTeacher.cshtml
@using MVC_workshop.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@model IEnumerable<MVC_workshop.Models.Course>
@inject UserManager<MVC_workshopUser> UserManager


@{
    ViewData["Title"] = "CoursesTeacher";
}

<h1 align="center">@ViewBag.Teacher - courses</h1>
<br/>
<form asp-controller="Courses" asp-action="CoursesTeacher" asp-route-userID=@UserManager.GetUserId(User)>
    <p>
        Search: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credits)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Programme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EducationLevel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Credits)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Programme)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EducationLevel)
            </td>
            <td>
                <a asp-controller="Enrollments" asp-action="StudentsEnCourse" asp-route-id="@item.Id" asp-route-tname="@ViewBag.Teacher">Students</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

MVC_workshop/Views/Courses/Create.cshtml
@model MVC_workshop.Models.Course

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credits" class="control-label"></label>
                <input asp-for="Credits" class="form-control" />
                <span asp-validation-for="Credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Programme" class="control-label"></label>
                <input asp-for="Programme" class="form-control" />
                <span asp-validation-for="Programme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EducationLevel" class="control-label"></label>
                <input asp-for="EducationLevel" class="form-control" />
                <span asp-validation-for="EducationLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstTeacherId" class="control-label"></label>
                <select asp-for="FirstTeacherId" class ="form-control" asp-items="ViewBag.FirstTeacherId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SecondTeacherId" class="control-label"></label>
                <select asp-for="SecondTeacherId" class ="form-control" asp-items="ViewBag.SecondTeacherId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_workshop/Views/Courses/Delete.cshtml
@model MVC_workshop.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Credits)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Credits)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programme)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EducationLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EducationLevel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstTeacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstTeacher.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondTeacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondTeacher.FirstName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC_workshop/Views/Courses/Details.cshtml
@model MVC_workshop.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Credits)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Credits)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programme)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EducationLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EducationLevel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstTeacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstTeacher.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondTeacher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondTeacher.FullName)
        </dd>
    </dl>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
         <span>|</span> <a asp-action="Index">Back to List</a>
    }
    @if (User.Identity.IsAuthenticated && User.IsInRole("Teacher"))
    {
        <a asp-action="CoursesTeacher" asp-route-id="@Model?.Id">Back to List</a>
    }
</div>

MVC_workshop/Views/Courses/Index.cshtml
@model IEnumerable<MVC_workshop.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<h1 align="center">Courses</h1>

<p>
    <a asp-action="Create" class="btn btn-secondary mb-3">New Course</a>
</p>
<form asp-controller="Courses" asp-action="Index" method="get">
    <p>
        Search: <input type="text" name="SearchString" />
        <input type="submit" value="Filter"/>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credits)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Programme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EducationLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstTeacher)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecondTeacher)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Credits)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Programme)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EducationLevel)
            </td>
            <td>
                 @if (item.FirstTeacherId != null)
                    {
                        @Html.DisplayFor(modelItem => item.FirstTeacherId)
                    }
                </td>
            <td>
                 @if (item.SecondTeacherId != null)
                {@Html.DisplayFor(modelItem => item.SecondTeacherId)}
            </td>
            <td>
                <a asp-controller="Students" asp-action="StudentsCourse" asp-route-id="@item.Id">Students</a> |
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>